### ISSUE TITLE
为啥我的composer 请求不到楼主的资源

### ISSUE THREAD

**Issue by feverrun** [jialeo/payment#4]
[Composer\Downloader\TransportException]
  The "https://packagist.phpcomposer.com/p/provider-2019-01%24a2ab395ccc6d6cfb3bd8f2171f38b595b23bf99bae0b8405f36f6f3295e3e4cb.json" file could not
   be downloaded (HTTP/1.1 404 Not Found)

**Comment by jialeo** [comment]
你好，你可以尝试切换回官方composer源

```
composer config -g repo.packagist composer https://repo.packagist.org
```

**Comment by feverrun** [comment]
谢谢！
